/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddUserResponse : Response containing the newly added user's details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddUserResponse {
    #[serde(rename = "user")]
    pub user: Box<models::UserResponse>,
}

impl AddUserResponse {
    /// Response containing the newly added user's details.
    pub fn new(user: models::UserResponse) -> AddUserResponse {
        AddUserResponse {
            user: Box::new(user),
        }
    }
}

