/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateDueRemainderRequest : Request body for creating a task due reminder.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDueRemainderRequest {
    /// Number of days before the due date to send the reminder.
    #[serde(rename = "days_before_due")]
    pub days_before_due: i32,
    /// If true, the reminder is sent when the task becomes overdue.
    #[serde(rename = "is_when_overdue")]
    pub is_when_overdue: bool,
    /// Frequency of the reminder (e.g., 'daily', 'weekly').
    #[serde(rename = "frequency")]
    pub frequency: String,
}

impl CreateDueRemainderRequest {
    /// Request body for creating a task due reminder.
    pub fn new(days_before_due: i32, is_when_overdue: bool, frequency: String) -> CreateDueRemainderRequest {
        CreateDueRemainderRequest {
            days_before_due,
            is_when_overdue,
            frequency,
        }
    }
}

