/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateTaskUserResponse : Response indicating whether users were successfully assigned to the task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTaskUserResponse {
    /// True if the assignment was successful.
    #[serde(rename = "success")]
    pub success: bool,
}

impl CreateTaskUserResponse {
    /// Response indicating whether users were successfully assigned to the task.
    pub fn new(success: bool) -> CreateTaskUserResponse {
        CreateTaskUserResponse {
            success,
        }
    }
}

