/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateTaskResponse : Response containing the newly created task's details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTaskResponse {
    #[serde(rename = "task")]
    pub task: Box<models::TaskResponse>,
}

impl CreateTaskResponse {
    /// Response containing the newly created task's details.
    pub fn new(task: models::TaskResponse) -> CreateTaskResponse {
        CreateTaskResponse {
            task: Box::new(task),
        }
    }
}

