/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteTaskResponse : Response indicating whether the task was successfully deleted.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTaskResponse {
    /// True if the task was deleted successfully.
    #[serde(rename = "success")]
    pub success: bool,
}

impl DeleteTaskResponse {
    /// Response indicating whether the task was successfully deleted.
    pub fn new(success: bool) -> DeleteTaskResponse {
        DeleteTaskResponse {
            success,
        }
    }
}

