/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteUserRequest : Request body for deleting a user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteUserRequest {
    /// Unique identifier of the user to delete.
    #[serde(rename = "id")]
    pub id: i32,
}

impl DeleteUserRequest {
    /// Request body for deleting a user.
    pub fn new(id: i32) -> DeleteUserRequest {
        DeleteUserRequest {
            id,
        }
    }
}

