/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteTaskUserResponse : Response indicating whether users were successfully unassigned from the task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTaskUserResponse {
    /// True if the unassignment was successful.
    #[serde(rename = "success")]
    pub success: bool,
}

impl DeleteTaskUserResponse {
    /// Response indicating whether users were successfully unassigned from the task.
    pub fn new(success: bool) -> DeleteTaskUserResponse {
        DeleteTaskUserResponse {
            success,
        }
    }
}

