/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteUserResponse : Response indicating whether the user was successfully deleted.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteUserResponse {
    /// True if the user was deleted successfully.
    #[serde(rename = "success")]
    pub success: bool,
}

impl DeleteUserResponse {
    /// Response indicating whether the user was successfully deleted.
    pub fn new(success: bool) -> DeleteUserResponse {
        DeleteUserResponse {
            success,
        }
    }
}

