/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteTaskUserRequest : Request body for unassigning users from a task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteTaskUserRequest {
    /// Identifier of the task.
    #[serde(rename = "task_id")]
    pub task_id: i32,
    /// List of user IDs to unassign from the task.
    #[serde(rename = "user_ids")]
    pub user_ids: Vec<i32>,
}

impl DeleteTaskUserRequest {
    /// Request body for unassigning users from a task.
    pub fn new(task_id: i32, user_ids: Vec<i32>) -> DeleteTaskUserRequest {
        DeleteTaskUserRequest {
            task_id,
            user_ids,
        }
    }
}

