/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FormResponse : Represents the response data for a submitted form.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FormResponse {
    /// Unique identifier for the form response.
    #[serde(rename = "id")]
    pub id: i32,
    /// Name of the form.
    #[serde(rename = "name")]
    pub name: String,
    /// Submitted data for the form's fields.
    #[serde(rename = "data")]
    pub data: Vec<serde_json::Value>,
    /// Timestamp when the form response was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp when the form response was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl FormResponse {
    /// Represents the response data for a submitted form.
    pub fn new(id: i32, name: String, data: Vec<serde_json::Value>, created_at: String, updated_at: String) -> FormResponse {
        FormResponse {
            id,
            name,
            data,
            created_at,
            updated_at,
        }
    }
}

