/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Form : Represents a form used for tasks or incidents.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Form {
    /// Name of the form.
    #[serde(rename = "name")]
    pub name: String,
    /// Structured data defining the form's fields and layout.
    #[serde(rename = "data")]
    pub data: Vec<serde_json::Value>,
    /// Timestamp when the form was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Timestamp when the form was last updated.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Unique identifier for the form.
    #[serde(rename = "id")]
    pub id: i32,
}

impl Form {
    /// Represents a form used for tasks or incidents.
    pub fn new(name: String, data: Vec<serde_json::Value>, id: i32) -> Form {
        Form {
            name,
            data,
            created_at: None,
            updated_at: None,
            id,
        }
    }
}

