/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTaskListResponse : Response containing a paginated list of tasks.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTaskListResponse {
    /// Total number of tasks matching the query.
    #[serde(rename = "total")]
    pub total: i32,
    /// Current page number.
    #[serde(rename = "page")]
    pub page: i32,
    /// Number of tasks per page.
    #[serde(rename = "page_size")]
    pub page_size: i32,
    /// List of tasks with related data.
    #[serde(rename = "data")]
    pub data: Vec<models::TaskListWithRelationsResponse>,
}

impl GetTaskListResponse {
    /// Response containing a paginated list of tasks.
    pub fn new(total: i32, page: i32, page_size: i32, data: Vec<models::TaskListWithRelationsResponse>) -> GetTaskListResponse {
        GetTaskListResponse {
            total,
            page,
            page_size,
            data,
        }
    }
}

