/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTaskResponse : Response containing the details of a single task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTaskResponse {
    #[serde(rename = "task")]
    pub task: Box<models::TaskWithRelationsResponse>,
}

impl GetTaskResponse {
    /// Response containing the details of a single task.
    pub fn new(task: models::TaskWithRelationsResponse) -> GetTaskResponse {
        GetTaskResponse {
            task: Box::new(task),
        }
    }
}

