/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetUpcomingTaskChartResponse : Response containing data for visualizing upcoming tasks grouped by due date.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpcomingTaskChartResponse {
    /// List of dates with corresponding task counts.
    #[serde(rename = "dates")]
    pub dates: Vec<models::TaskCountsByDateInner>,
}

impl GetUpcomingTaskChartResponse {
    /// Response containing data for visualizing upcoming tasks grouped by due date.
    pub fn new(dates: Vec<models::TaskCountsByDateInner>) -> GetUpcomingTaskChartResponse {
        GetUpcomingTaskChartResponse {
            dates,
        }
    }
}

