/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetTasksByIncidentResponse : Response containing a list of tasks associated with an incident result.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTasksByIncidentResponse {
    /// List of tasks linked to the incident result.
    #[serde(rename = "tasks")]
    pub tasks: Vec<models::TaskWithRelationsResponse>,
}

impl GetTasksByIncidentResponse {
    /// Response containing a list of tasks associated with an incident result.
    pub fn new(tasks: Vec<models::TaskWithRelationsResponse>) -> GetTasksByIncidentResponse {
        GetTasksByIncidentResponse {
            tasks,
        }
    }
}

