/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReportFormat : Format of a generated report: 'xlsx' for Excel files, 'pdf' for PDF documents.
/// Format of a generated report: 'xlsx' for Excel files, 'pdf' for PDF documents.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportFormat {
    #[serde(rename = "xlsx")]
    Xlsx,
    #[serde(rename = "pdf")]
    Pdf,

}

impl std::fmt::Display for ReportFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Xlsx => write!(f, "xlsx"),
            Self::Pdf => write!(f, "pdf"),
        }
    }
}

impl Default for ReportFormat {
    fn default() -> ReportFormat {
        Self::Xlsx
    }
}

