/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignUpUserRequest : Request body for signing up a new user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignUpUserRequest {
    /// The user's first name.
    #[serde(rename = "first_name")]
    pub first_name: String,
    /// The user's last name.
    #[serde(rename = "last_name")]
    pub last_name: String,
    /// The user's email address.
    #[serde(rename = "email")]
    pub email: String,
    /// The user's password.
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "role")]
    pub role: models::UserRole,
    /// Optional URL to redirect the user after signup, if applicable.
    #[serde(rename = "redirect_url", skip_serializing_if = "Option::is_none")]
    pub redirect_url: Option<String>,
}

impl SignUpUserRequest {
    /// Request body for signing up a new user.
    pub fn new(first_name: String, last_name: String, email: String, password: String, role: models::UserRole) -> SignUpUserRequest {
        SignUpUserRequest {
            first_name,
            last_name,
            email,
            password,
            role,
            redirect_url: None,
        }
    }
}

