/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskResponse : Represents a task's core details, used in responses for task creation and updates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskResponse {
    /// Unique identifier for the task.
    #[serde(rename = "id")]
    pub id: i32,
    /// Name or title of the task.
    #[serde(rename = "name")]
    pub name: String,
    /// Identifier of the user who created the task.
    #[serde(rename = "author_id")]
    pub author_id: i32,
    /// Detailed description of the task's purpose or requirements.
    #[serde(rename = "description")]
    pub description: String,
    /// Identifier of the form associated with the task.
    #[serde(rename = "form_id")]
    pub form_id: i32,
    /// Indicates whether the task must be completed by all employees.
    #[serde(rename = "is_every_employee_needs_to_complete")]
    pub is_every_employee_needs_to_complete: bool,
    /// Rule defining the task's recurrence pattern (e.g., 'daily', 'weekly'), if applicable.
    #[serde(rename = "recurrency_rule", skip_serializing_if = "Option::is_none")]
    pub recurrency_rule: Option<String>,
    #[serde(rename = "priority")]
    pub priority: models::TaskPriority,
    /// Initial due date for the task.
    #[serde(rename = "first_due_date")]
    pub first_due_date: String,
    /// Timestamp when the task was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Timestamp when the task was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    /// Timestamp when the task becomes active.
    #[serde(rename = "start_date")]
    pub start_date: String,
}

impl TaskResponse {
    /// Represents a task's core details, used in responses for task creation and updates.
    pub fn new(id: i32, name: String, author_id: i32, description: String, form_id: i32, is_every_employee_needs_to_complete: bool, priority: models::TaskPriority, first_due_date: String, created_at: String, updated_at: String, start_date: String) -> TaskResponse {
        TaskResponse {
            id,
            name,
            author_id,
            description,
            form_id,
            is_every_employee_needs_to_complete,
            recurrency_rule: None,
            priority,
            first_due_date,
            created_at,
            updated_at,
            start_date,
        }
    }
}

