/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskCountsByDateInner {
    /// Due date for the tasks.
    #[serde(rename = "date")]
    pub date: String,
    /// Number of tasks due on this date.
    #[serde(rename = "task_count")]
    pub task_count: i32,
}

impl TaskCountsByDateInner {
    pub fn new(date: String, task_count: i32) -> TaskCountsByDateInner {
        TaskCountsByDateInner {
            date,
            task_count,
        }
    }
}

