/*
 * Vestra Compliance API
 *
 * Vestra Compliance Backend REST API for managing users, tasks, and compliance-related operations. This is version 1.0; future versions may introduce breaking changes. All endpoints require authentication unless explicitly stated otherwise.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : Represents a simplified user entity for use in task relations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// Unique identifier for the user.
    #[serde(rename = "id")]
    pub id: i32,
    /// User's first name.
    #[serde(rename = "first_name")]
    pub first_name: String,
    /// User's last name.
    #[serde(rename = "last_name")]
    pub last_name: String,
    /// User's email address.
    #[serde(rename = "email")]
    pub email: String,
    /// URL to the user's avatar image, if available.
    #[serde(rename = "avatar_url", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    /// Timestamp when the user was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Timestamp when the user was last updated.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl User {
    /// Represents a simplified user entity for use in task relations.
    pub fn new(id: i32, first_name: String, last_name: String, email: String) -> User {
        User {
            id,
            first_name,
            last_name,
            email,
            avatar_url: None,
            created_at: None,
            updated_at: None,
        }
    }
}

